name: Test Report

on:
  workflow_run:
    workflows: [ "Build and Test" ]
    types:
      - completed

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Display structure of downloaded files
        run: ls -R

      - name: JUnit report
        uses: dorny/test-reporter@v1
        with:
          artifact: build-reports
          name: JUnit tests
          path: 'test-results/test/*.xml'
          reporter: java-junit

      - name: TextTest report
        uses: dorny/test-reporter@v1
        with:
          artifact: build-reports
          name: TextTest tests
          path: 'test-results/texttest/**/*.xml'
          reporter: java-junit

