name: Test Report

on:
  workflow_run:
    workflows: [ "Build and Test" ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: JUnit report
        uses: dorny/test-reporter@v1
        with:
          artifact: build-reports
          name: JUnit tests
          path: 'test-results/test/*.xml'
          reporter: java-junit

      - name: TextTest report
        uses: dorny/test-reporter@v1
        with:
          artifact: build-reports
          name: TextTest tests
          path: 'test-results/texttest/**/*.xml'
          reporter: java-junit

